#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
#spring:
#  application:
#    name: UserProfileService
#  data:
#   mongodb:
#     username: ${MONGO_USER}
#     password: ${MONGO_PASSWORD}
#     database: ${MONGO_DATABASE}
#     port: ${MONGO_PORT}
#     host: ${MONGO_HOST}
#server:
# port: 8084
# 
#eureka:
#  client:
#    service-url:
#      default-zone: http://localhost:8761/eureka
#      register-with-eureka: true
#      fetch-registry: true
spring:
  application:
    name: UserProfileService
  data:
   mongodb:
     database: userprofileservice
     port: 27017
     host: localhost
#     port: ${MONGO_PORT}
#     host: ${MONGO_HOST}
server:
 port: 8084
 connection-timeout: 1500

#
